[profile.default]
remappings = [
	'@chainlink/contracts/=lib/chainlink/contracts/',
	'@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
]
src = "src"
out = "out"
libs = ["lib"]

solc = '0.8.28' # Solidity compiler version
optimizer = true # Enable optimizer
optimizer_runs = 200 
ast = true
ffi = true
build_info = true
extra_output = ["storageLayout"]
